# Generated by Django 5.1.4 on 2025-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('sleep_duration', models.FloatField()),
            ],
        ),
    ]
